[package]
name = "reserver-backend"
version = "0.0.1-alpha.1"
authors = ["Andrei Ormanji <andrew.ormanzhi@gmail.com>"]
edition = "2021"

[dependencies]
actix-cors = "0.6.0-beta.8"
actix-identity = "0.3"
actix-redis = "0.9"
actix-tls = "3.0.0"
actix-web = "4.0.0-beta.18"
actix-web-grants = "2.2"
actix-web-httpauth = "0.6.0-beta.7"
actix-web-validator = "2.2"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.9"
futures = "0.3"
futures-util = "0.3"
log = "0.4"
sea-orm = { version = "^0", features = [
    "debug-print",
    "sqlx-mysql",
    "runtime-actix-native-tls",
    "macros",
    "with-json",
    "with-chrono",
    "with-rust_decimal",
    "with-uuid",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_qs = "0.8"
serde_urlencoded = "0.7"
# sqlx = {version = "0.5", features = [ "runtime-actix-native-tls", "macros", "migrate", "uuid", "mysql", "chrono", "json" ]}
tokio = "1.14"
validator = { version = "0.14", features = ["derive", "validator_derive"] }

[dev-dependencies]
sea-orm = { version = "^0", features = [
    "debug-print",
    "mock",
    "sqlx-mysql",
    "runtime-actix-native-tls",
    "macros",
    "with-json",
    "with-chrono",
    "with-rust_decimal",
    "with-uuid",
], default-features = false }